<template>
    <x-number-input
        placeholder="数字输入"
        number-button
        clearable
        step="2"
        block
    />
    <x-number-input
        placeholder="数字输入"
        number-button
        clearable
        :step="3"
        block
    />
</template>